name: build.yml

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:

  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup (MacOS)
      if:   matrix.os == 'macos-latest'
      run:  ./scripts/prebuild_macos.sh

    - name: Setup (Ubuntu)
      if:   matrix.os == 'ubuntu-latest'
      run:  ./scripts/prebuild_ubuntu.sh

    - name: Setup (Windows)
      if:   matrix.os == 'windows-latest'
      run:  cmd /c ".\scripts\prebuild_windows.bat"

    - name: Build (MacOS)
      if:   matrix.os == 'macos-latest'
      run:  ./scripts/build_macos.sh

    - name: Build (Ubuntu)
      if:   matrix.os == 'ubuntu-latest'
      run:  ./scripts/build_ubuntu.sh

    - name: Build (Windows)
      if:   matrix.os == 'windows-latest'
      run:  cmd /c ".\scripts\build_windows.bat"

    - name: Test (MacOS)
      if:   matrix.os == 'macos-latest'
      run:  ./scripts/postbuild_macos.sh

    - name: Test (Ubuntu)
      if:   matrix.os == 'ubuntu-latest'
      run:  ./scripts/postbuild_ubuntu.sh

    - name: Test (Windows)
      if:   matrix.os == 'windows-latest'
      run:  cmd /c ".\scripts\postbuild_windows.bat"

    - name: Upload build artifacts
      if:   github.event_name == 'push'
      uses: actions/upload-artifact@master
      with:
        name: StftPitchShiftPlugin-${{matrix.os}}
        path: ./build/StftPitchShiftPlugin_artefacts/Release

  publish-release:

    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write

    steps:

    - name: Download all build artifacts
      uses: actions/download-artifact@master
      with:
        path: release-artifacts

    - name: Upload build artifacts to release
      uses: softprops/action-gh-release@master
      with:
        files: release-artifacts/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
